= SQL Server

== Config

* `/opt/mssql/bin/mssql-conf list` - list config options (need to run under root, in docker login exec in the container with `-u 0` option)

== CDC

* `SELECT * FROM msdb.dbo.cdc_jobs;` - show CDC jobs and their params
* `exec sys.sp_cdc_change_job @job_type = 'capture', @pollinginterval = 1;` - change polling interval to 1 second (default is 5)

== Common

* all commands are triggered by separate `go` command

* `SELECT Name FROM sys.databases;` - list databases
* `use testDB1;` - switch DB
* `SELECT * FROM INFORMATION_SCHEMA.TABLES;` - list all tables

== Info

* `select @@version;` - shows DB version
* `select db_name();` - DB name

== Indexes

* `SELECT name FROM sys.indexes WHERE object_id = (SELECT object_id FROM sys.objects WHERE name = 'table_name');` - show names of indexes on table `table_name`

== Locks

* `SELECT * FROM sys.dm_tran_locks WHERE request_session_id = @@SPID;`
* `SELECT resource_type,request_mode,request_status FROM sys.dm_tran_locks WHERE request_session_id = @@SPID;`

```
1> begin transaction
2> insert into tablea values (1, 'aaa');
3> SELECT resource_type,request_mode,request_status FROM sys.dm_tran_locks WHERE request_session_id = @@SPID;
4> commit
5> go
```

* `ALTER INDEX index_name ON table_name SET (ALLOW_PAGE_LOCKS = OFF);` - turn off page lock of the `index_name` on table `table_name`

== Transactions

* `SELECT transaction_isolation_level FROM sys.dm_exec_sessions WHERE session_id = @@SPID;` - show current isolation levels (list of constants is https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-sessions-transact-sql[sys.dm_exec_sessions])
* `SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;` - change isolation level


== DB log

* `SELECT [Transaction ID],[Transaction Name], [Operation], [Context], [Transaction SID] FROM fn_dblog (null,null) where [Transaction Name]='INSERT';` - select `insert` operations from server log
* `SELECT SUSER_SNAME(0x01);` - shows username for given SID (`[Transaction SID]` from previous command)


== Help

* `exec sp_help` - list all the objects in the database
* `sp_help $object` - list information about given object (e.g. `'sys.fn_dblog'`)

== SQL Agent

* `EXEC xp_servicecontrol N'Querystate|Start|Stop',N'Service Name'` - start/stop specified service
* `EXEC xp_servicecontrol N'querystate',N'SQLServerAGENT';` - show status if SQL Agent
