= Virt builder

* `virt-builder centos-7.7 --size 10G --format qcow2 --root-password=password:passwd -o /home/vjuranek/images/vm/centos77.img`
* `virt-builder fedora-29 --root-password=password:heslo -o ./fc29.img`

= guestfish

Command-line tool for examining and modifying virtual machine filesystems, see http://libguestfs.org/guestfish.1.html


* `virt-sparsify`
* `virt-customize`

== Editing disk

* `guestfish --rw -a ./CentOS-Stream.qcow2`
* `run`
* `list-filesystems`

    /dev/sda1: xfs

* `mount /dev/sda1 /`
* `vi /etc/shadow` - change root password (use e.g. `openssl passwd -6 passwd` or `mkpasswd` to generate the hash)
* `quit`

= virt-install

* `virt-install --name fc34-test --memory 2048 --vcpus 1 --disk /home/vjuranek/images/test.img,bus=sata --import --os-variant fedora34 --network default`
* `virt-install --osinfo list`
* `virt-install --name centos10 --osinfo detect=on,name=centos-stream9 --memory 2048 --vcpus 2 --disk ~images/vm/centos10.img,size=20 --location ~/images/iso/CentOS-Stream-10-latest-x86_64-dvd1.iso`
