= Docker

== Useful commands

* `docker container exec  -it $CONATINER_NAME /bin/bash` - run shell inside running container
* `docker rm `docker ps -a -q`` - remove all containers
* `docker inspect -f {{.NetworkSettings.Networks.docker_default.IPAddress}} $CONTAINER_ID` - shows IP address of the container

== Network

* `docker network ls` - list docker networks
* `docker run -it --rm --name mycontainer --link $CONTAINER_NAME --net $NETWOTK_NAME ...` - links to conatiner in given network
* `--net=host` - add to docker command to expose ports available on the local host machine

== Cleanup

* `docker volume prune` - removed unsed volumes
* `docker image prune -a --force --filter "until=2022-08-01T00:00:00"` - prune images older than specified date

* see also https://docs.docker.com/config/pruning/

== Resources

* `docker run --cpus=".5"` - how many CPUs container can use, in this case max 0.5 CPU

== Isseus

=== OOM

Failure:

```
===> Launching kafka ... 
library initialization failed - unable to allocate file descriptor table - out of memorylibrary initialization failed - unable to allocate file descriptor table - out of memoryAborted (core dumped)
```

Fix:

* add `--default-ulimit nofile=65536:65536` to `ExecStart` command into `docker.service` file:

```
ExecStart=/usr/bin/dockerd --default-ulimit nofile=65536:65536 -H fd:// --containerd=/run/containerd/containerd.sock
```

follewed by `systemctl daemon-reload` and `systemctl restart docker`
