= JVM

== Java major version numbers

* https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers

== JVM flags

=== TLAB

* `-XX:-UseTLAB` - turn off TLAB (on by default).
* `-XX:+PrintTLAB` - log TLAB usage during each minor GC. `desired_size` is current TLAB size.
* `-XX:TLABSize` - initial size of TLAB.
* `-XX:MinTLABSize` - minimal TLAB size (`-XX:TLABSize` cannot be smaller than this value).
* `-XX:ResizeTLAB` - allows JVM to resize TLAB size dynamically (turn on by default).
* `-XX:TLABWasteTargetPercent=N` - threshold for allocating object outside TLAB, so called slow allocation (for objects under this limit which doesn't fit into existing TLAB, new TLAB is created, unused rest of the old TLAB is waste). Default is 1 (1% of TLAB size).
* `-XX:TLABWasteIncrement=N` - how much is `TLABWasteTargetPercent` automatically incremented after each slow allocation. The default is 4 (4%).

=== Debug options

* `-Djavax.net.debug=all` - debug all net comminucation, good for debugging e.g. varisou SSL issues (see also https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/ReadDebug.html)

== Security

* in case of e.g. `javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)` can be workaround by commeting out `jdk.tls.disabledAlgorithms` in ``java.security` file (`/usr/java/latest/conf/security/java.security`)
