= Oracle DB

== Basic commands

* `SELECT table_name FROM user_tables ORDER BY table_name;` - list tables
* `SELECT table_name FROM all_tables ORDER BY table_name;` - list all tables

* `select name from V$DATAFILE;` - list database files

== Connections, sessions, processes

* `SELECT name, value FROM v$parameter WHERE name = 'sessions';` - maximum allowed sessions
* `show parameter sessions;` - same as above (shows all `*sessions*` parameters)
* `SELECT count(*) FROM V$SESSION;` - number of current active sessions

* `show parameter process;` - `processes` shows the configured limit for the number of processes
* `select count(*) from V$PROCESS;` - number or running processes

== Alert log

* `$ORACLE_DIR/diag/rdbms/$DB_NAME/$SID/trace` - location of alert logs (e.g. `/opt/oracle/diag/rdbms/orclcdb/ORCLCDB/trace/`)
* `select value from GV$DIAG_INFO WHERE name='Diag Trace';` - shows location of alert logs
* `archive log list;`

* `alter session set container=cdb$root;`
* `alter system switch logfile;`

== Redo logs

* `select GROUP#,TYPE,MEMBER from v$logfile;` - list redo log files
* `select GROUP#,THREAD#,bytes,MEMBERS,STATUS from v$log;` - list other redo log file details, especially status
* `alter system switch logfile;` - switch the redo log file

== PDB

* `show pdbs;`
* `alter session set container=cdb$root;` - switch to CDB root database
* `select name from v$pdbs;`

== LogMiner

* `desc v$logmnr_contents;`

