= iSCSI

== Target

=== Installation

* `dnf -y install targetcli`

=== Target setup

* `targetcli /iscsi/ create iqn.2016-01.com.ovirt:444`
* `targetcli /iscsi/iqn.2016-01.com.ovirt:444/tpg1/ set attribute authentication=0 demo_mode_write_protect=0 generate_node_acls=1 cache_dynamic_acls=1`
* `targetcli /backstores/fileio/ create disk01 /srv/storage/disk01.img 3G`
* `targetcli /iscsi/iqn.2016-01.com.ovirt:444/tpg1/luns create /backstores/fileio/disk01`
* `targetcli /`
* `targetcli saveconfig`
* `systemctl enable target`

=== Firewall setup

* `firewall-cmd --add-service=iscsi-target`
* `firewall-cmd --add-service=iscsi-target --permanent`
* `firewall-cmd --add-port=860/tcp`
* `firewall-cmd --add-port=860/tcp --permanent`
* `firewall-cmd --reload`

=== Info

* `targetcli /backstores/fileio/ status`
* `targetcli /backstores/fileio/ ls`


== Remove

=== Remove LUNs

* `targetcli /iscsi/iqn.2016-01.com.ovirt:444/tpg1/luns delete <LUN_NUMBER>`

=== Issues

==== qemu-img got stuck

===== Isssue
`qemu-img` got stuck during copying from one iscsi to another with and on the targer `dmesg` is `WRITE_SAME sectors: 65535 exceeds max_write_same_len: 4096`

===== Fix
Actually doesn't fully fix it, but solve issue with `max_write_same_len`:

```
targetcli /backstores/fileio/my-disk set attribute \
    emulate_tpu=1 \
    emulate_tpws=1 \
    max_write_same_len=65335
```

See https://lists.ovirt.org/archives/list/devel@ovirt.org/thread/ZDNOVHOANZSMXN5WM73LQPKX3UEGBFV3/

== Initiator

=== Installation

* `dnf install iscsi-initiator-utils`


=== Connecting to target

* `iscsiadm --mode discoverydb --type sendtargets --portal $TARGET_IP --discover`
* `iscsiadm --mode node --targetname iqn.2016-01.com.ovirt:444 --portal $TARGET_IP -l` -  login to target
* `iscsiadm --mode node --targetname iqn.2016-01.com.ovirt:444 --portal $TARGET_IP -u` - logout from target

=== Info

* `iscsiadm -m session` - show active sessions
* `iscsiadm -m session  -P 3` - detail list

* `cat /proc/scsi/scsi`

=== Issues

* use IPv4 address instead hostname to avoid connection issue when IPv6 is not setup properly (nad hostname resolves to IPv6 address)


= SCSI utils

* `sg_turs` - send one or more SCSI TEST UNIT READY commands
* `sg_turs /dev/sdX; echo $?` - if `0`, device is ready
* `sg_inq /dev/sdb` - issue SCSI INQUIRY command, e.g. to check if LUN is SPC3 compliant (output contains `[SPC-3]`)
* `sg_persist` - manage SCSI reservation (see also `mpathpersist` for multipath equivalent)
* `sg_persist --in -k -d /dev/sbd` - view the keys registered on a LUN
* `sg_persist --in -r -d /dev/sdb` - view the reservations on a LUN
* `sg_persist --in -s -d /dev/sdb` -  to view more info
* `sg_persist --out --register --param-sark=<KEY> /dev/sdb` - to register a key
* `sg_persist --out --reserve --param-rk=<KEY> --prout-type=<TYPE> /dev/sdb` - to reserve registered key:
** 1 write exclusive
** 3 exclusive access
** 5 write exclusive - registrants only
** 6 exclusive access - registrants only
** 7 write exclusive - all registrants
** 8 exclusive access - all registrants.
* `sg_persist --out --release --param-rk=<KEY> --prout-type=<TYPE> /dev/sdb` - to relase a reservation
* `sg_persist --out --register --param-rk=<KEY> /dev/sdb` - to unregister a key
* `sg_persist --out --clear --param-rk=<KEY> /dev/sbd` -  to clear the reservation and all registered keys
