= iSCSI

== Target

=== Installation

* `yum -y install targetcli`

=== Target setup

* `targetcli /iscsi/ create iqn.2016-01.com.ovirt:444`
* `targetcli /iscsi/iqn.2016-01.com.ovirt:444/tpg1/ set attribute authentication=0 demo_mode_write_protect=0 generate_node_acls=1 cache_dynamic_acls=1`
* `targetcli /backstores/fileio/ create disk01 /srv/storage/disk01.img 3G`
* `targetcli /iscsi/iqn.2016-01.com.ovirt:444/tpg1/luns create /backstores/fileio/disk01`
* `targetcli /`
* `targetcli saveconfig`
* `systemctl enable target`

=== Firewall setup

* `firewall-cmd --add-service=iscsi-target`
* `firewall-cmd --add-service=iscsi-target --permanent`
* `firewall-cmd --add-port=860/tcp`
* `firewall-cmd --add-port=860/tcp --permanent`
* `firewall-cmd --reload`

=== Info

* `targetcli /backstores/fileio/ status`
* `targetcli /backstores/fileio/ ls`


=== Issues

==== qemu-img got stuck

===== Isssue
`qemu-img` got stuck during copying from one iscsi to another with and on the targer `dmesg` is `WRITE_SAME sectors: 65535 exceeds max_write_same_len: 4096`

===== Fix
Actually doesn't fully fix it, but solve issue with `max_write_same_len`:

```
targetcli /backstores/fileio/my-disk set attribute \
    emulate_tpu=1 \
    emulate_tpws=1 \
    max_write_same_len=65335
```

See https://lists.ovirt.org/archives/list/devel@ovirt.org/thread/ZDNOVHOANZSMXN5WM73LQPKX3UEGBFV3/

== Initiator

* `iscsiadm --mode discoverydb --type sendtargets --portal $TARGET_IP --discover`
* `iscsiadm --mode node --targetname iqn.2016-01.com.ovirt:444 --portal $TARGET_IP --login`
* `cat /proc/scsi/scsi`
