= RPM

* `rpm -q --scripts <package>` - list pre-install and post-install scripts run by installed packed
* `rpm -e --nodeps <package>` - removes package without checking dependecies

= Yum/dnf

* `yum list $package --showduplicates` - show all avilable package versions
* `yum install $packge_name-$version_info` - installs or update specified package version
* `yum downgrade $package_name-$version_info` - downgrades to specified version
* `dnf list available $package_name` - shows all available package vesrions (`yum list --showduplicates $package_name` should work as well)
* `yum-builddep $pkg` - install build dependencies for package or spec file

== Repo setup

=== Repo from DVD/ISO

* `mkdir -p  /mnt/dvd`
* `mount -o loop /dev/sr0 /mnt/dvd`
* `mount /dev/sr0  /mnt/dvd`
* `cp /mnt/disc/media.repo /etc/yum.repos.d/rhel8-dvd.repo`
* `vi /etc/yum.repos.d/rhel8-dvd.repo`

[source, shell]
----
[BaseOS]
name=Red Hat Enterprise Linux 8.1.0 BaseOS
baseurl=file:///mnt/dvd/BaseOS
gpgcheck=0

[AppStream]
name=Red Hat Enterprise Linux 8.1.0 Appstream
baseurl=file:///mnt/dvd/AppStream
gpgcheck=0
----

== Yum utils

* `yum install yum-utils`
* `dnf repoquery -i $pkg` - which repo contains package `pkg` (on CentOS/RHEL with `yum`: `repoquery -i $pkg`)

== Transactions

* `dnf history list` - list transactions
* `dnf history undo $id` - reverts transaction `$id`	
