= Git howto

== Commits

* `git commit --amend --author="name <email>"` - change commit author of the last commit
* `git commit --amend --date="2021-04-06 09:00:00"` - change commit date
* `git commit --amend --date=now --no-edit` - amend commit date to current time

To edit more/older commits:

* `git rebase -i HEAD~X`
* use `edit` for commits to be changed
* `git commit --amend --author="name <email>"`
* `git rebase --continue`

* `git reset HEAD^` - remove last commit, but keep files changed

* `git describe <commit>` - find most recent tag that is reachable from this commit (i.e. in which tag this commit is contained)

* `git reflog` - log of operations with commit refferences

* `git cherry-pick -X theirs <commit-hash>` - cherry-pick the commit and applies `theirs` merge option strategy. Can be use to re-apply the commit.

=== Staging

* `git add -i` - interactive staging (see https://git-scm.com/book/en/v2/Git-Tools-Interactive-Staging)
* `git add -p` - interactive patch staging (staging parts of file), also very useful to use `git gui` which has better granularity

=== Rebase

* `git rebase -i --root` - rebase to the first commit

== Tags

* `git tag -d tag_name` - delete `tag_name` locally
* `git push --delete upstream tag_name` - delete `tag_name` in remote `upstream` repo

== Git log

* `git log a..b` - git log in range from commit hash `a` to `b`
* `git log --grep=bug_url` - selects only commit which message contains `bug_url` (in general any pattern)
* `git log --grep=$pattern --pretty=format:"%h"` - select commit containing <patter> and show only short commit hashes (`%H` for full commit hash)
* `git log --author=vjuranek@rh.c --pretty=format:"%h %an %s"` - my commits, containing short hash, commiter name (to double check:-) and commit subject

=== Removed file

* `git log -p --full-history -- "+**/file_name.*+"` - git log for a file which was already deleted
* `git log -p --full-history -- <path-to-file>`

== Git grep

* `git grep $PATTERN -- ':(exclude)*/test/*'` - git grep for `$PATTERN`, but exclude all test directories

== Git email

* `dnf install git-email`
* `git format-patch -N --to=to@email --cc=cc1@email --cc=cc2@email` - formats last N patches and sets TO and CC emails
** to change subject (e.g. to include patch version), use `--subject-prefix="PATCH vX"`
** to include cover latter, add `--cover-letter` and edit appropriate patch `0000-cover-letter.patch`, replacing all `***` (subject and body)
* `git send-email --smtp-server=smtp.server.addr *.patch` - sends the patches

== Worktree

* `git worktree list` - list work trees
* `git worktree move WORK_TREE_NAME PATH` - move worktree named `WORK_TREE_NAME` to dir `PATH`


== Git crypt

* `git crypt status -e` - list encrypted files
* `git crypt unlock` - unlock encrypted files

=== Adding new collaborator

* `gpg --armor --export DBD9D3A4D99067D0CE19663B1C013860708AA44E` - export public gpg key

* `gpg --import DBD9D3A4D99067D0CE19663B1C013860708AA44E.gpg` - import user gpg public key
* `gpg --list-keys` - list keys to check it's imported
* `gpg --edit-key DBD9D3A4D99067D0CE19663B1C013860708AA44E`
* `> trust` - change tru level fo the key to 5 (ultimate)
* `> save` - save changes and list key again to see it the change were applied
* `git-crypt add-gpg-user DBD9D3A4D99067D0CE19663B1C013860708AA44E`

== SSL

* `git -c http.sslVerify=false clone https://repo.using.self.signed.cert` - clone repo and skip certificate check

== GitHub

* `git fetch upstream pull/<PR_NUMBER>/head:<LOCAL_BRANCH>` - pulls PR `#<PR_NUMER>` into local `<LOCAL_BRANCH>`


== Troubleshooting

* issue with TODO list during rebase (cannot lock rebase) - delete `.git/REBASE_HEAD`
