= Git howto

== Commits

* `git commit --amend --author="name <email>"` - change commit author of the last commit

== Git log

* `git log a..b` - git log in range from commit hash `a` to `b`
* `git log --grep=bug_url` - selects only commit which message contains `bug_url` (in general any pattern)
* `git log --grep=$pattern --pretty=format:"%h"` - select commit containing <patter> and show only short commit hashes (`%H` for full commit hash)
* `git log --author=vjuranek@rh.c --pretty=format:"%h %an %s"` - my commits, containing short hash, commiter name (to double check:-) and commit subject

== Git email

* `dnf install git-email`
* `git format-patch -N --to=to@email --cc=cc1@email --cc=cc2@email` - formats last N patches and sets TO and CC emails
** to change subject (e.g. to include patch version), use `--subject-prefix="PATCH vX"`
** to include cover latter, add `--cover-letter` and edit appropriate patch `0000-cover-letter.patch`, replacing all `***` (subject and body)
* `git send-email --smtp-server=smtp.server.addr *.patch` - sends the patches
