= Git howto

== Commits

* `git commit --amend --author="name <email>"` - change commit author of the last commit
* `git commit --amend --date="2021-04-06 09:00:00"` - change commit date

To edit more/older commits:

* `git rebase -i HEAD~X`
* use `edit` for commits to be changed
* `git commit --amend --author="name <email>"`
* `git rebase --continue`

* `git reset HEAD^` - remove last commit, but keep files changed

* `git describe <commit>` - find most recent tag that is reachable from this commit (i.e. in which tag this commit is contained)

=== Rebase

* `git rebase -i --root` - rebase to the first commit

== Git log

* `git log a..b` - git log in range from commit hash `a` to `b`
* `git log --grep=bug_url` - selects only commit which message contains `bug_url` (in general any pattern)
* `git log --grep=$pattern --pretty=format:"%h"` - select commit containing <patter> and show only short commit hashes (`%H` for full commit hash)
* `git log --author=vjuranek@rh.c --pretty=format:"%h %an %s"` - my commits, containing short hash, commiter name (to double check:-) and commit subject

=== Removed file

* `git log -p --full-history -- "+**/file_name.*+"` - git log for a file which was already deleted
* `git log -p --full-history -- <path-to-file>`

== Git email

* `dnf install git-email`
* `git format-patch -N --to=to@email --cc=cc1@email --cc=cc2@email` - formats last N patches and sets TO and CC emails
** to change subject (e.g. to include patch version), use `--subject-prefix="PATCH vX"`
** to include cover latter, add `--cover-letter` and edit appropriate patch `0000-cover-letter.patch`, replacing all `***` (subject and body)
* `git send-email --smtp-server=smtp.server.addr *.patch` - sends the patches
